=== RHInception/re-common/schemas/recore_deployment.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": false,
    "title": "re-core deployment message format",
    "description": "While executing releases, the re-core component emits messages in one of three formats. The format selected is determined by the type of execution step being ran. For more information: http://release-engine.readthedocs.org/en/latest/messageformats.html#deployment-message-formats",

    "definitions": {
	"parameters": {
	    "type": "object",
	    "properties": {
		"hosts": {
		    "type": "array",
		    "minItems": 1,
		    "items": {
			"type": "string"
		    }
		},
		"subcommand": { "type": "string" },
		"command": { "type": "string" },
        "tries": { "type": "number" },
        "check_scripts": { "type": "array", "items": {"type": "string"}}
	    },
	    "additionalProperties": true
	},
	"dynamic": {
	    "type": "object"
	},
	"group": {
	    "type": "string"
	},
        "notify": {
            "type": "object",
            "properties": {
                "started": {"$ref": "#/definitions/notify_endpoints"},
                "completed": {"$ref": "#/definitions/notify_endpoints"},
                "failed": {"$ref": "#/definitions/notify_endpoints"}
            },
            "additionalProperties": false
        },
        "notify_endpoints": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    },


    "properties": {
	"parameters": {"$ref": "#/definitions/parameters"},
	"dynamic": {"$ref": "#/definitions/dynamic"},
	"group": {"$ref": "#/definitions/group"},
	"notify": {"$ref": "#/definitions/notify"}
    },

    "required": [ "parameters", "dynamic", "group", "notify" ]
}

=== RHInception/re-common/documents/recore_deployment_dynamic_valid.json
{
    "parameters": {
        "command": "juicer",
        "dynamic": [
            "cart",
            "environment"
        ],
        "subcommand": "Promote",
        "hosts": [
            "host01.example.com"
        ]
    },
    "group": "test",
    "dynamic": {
        "cart": "bitmath",
        "environment": "re"
    },
    "notify": {}
}

=== RHInception/re-common/documents/recore_deployment_argument_valid.json
{
    "parameters": {
        "service": "megafrobber",
        "hosts": [
            "host01.example.com"
        ],
        "subcommand": "Restart",
        "command": "service",
        "tries": 5,
        "check_scripts": ["doesitwork"]
    },
    "group": "test",
    "dynamic": {},
    "notify": {}
}
